# Generated by Django 6.1 on 2026-09-10 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('competition', 'Competition'), ('scholarship', 'Scholarship')], default='full-time', max_length=20)),
                ('issuer', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='credentials/')),
            ],
        ),
    ]
