# Generated by Django 6.1 on 2026-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='category',
            field=models.CharField(choices=[('certification', 'Certification'), ('award', 'Award'), ('competition', 'Competition'), ('scholarship', 'Scholarship')], default='certification', max_length=20),
        ),
    ]
