# Generated by Django 6.1 on 2026-10-01 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_experience_starred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
